/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/users/': RouteRecordInfo<'/users/', '/users', Record<never, never>, Record<never, never>>,
    '/users/[id]/details': RouteRecordInfo<'/users/[id]/details', '/users/:id/details', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/users/[id]/edit': RouteRecordInfo<'/users/[id]/edit', '/users/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/users/[id]/edit/': RouteRecordInfo<'/users/[id]/edit/', '/users/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/users/[id]/edit/[...path]': RouteRecordInfo<'/users/[id]/edit/[...path]', '/users/:id/edit/:path(.*)', { id: ParamValue<true>, path: ParamValue<true> }, { id: ParamValue<false>, path: ParamValue<false> }>,
    '/users/[id]/edit/confirm': RouteRecordInfo<'/users/[id]/edit/confirm', '/users/:id/edit/confirm', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/users/[id]/edit/input': RouteRecordInfo<'/users/[id]/edit/input', '/users/:id/edit/input', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/users/list': RouteRecordInfo<'/users/list', '/users/list', Record<never, never>, Record<never, never>>,
    '/users/new': RouteRecordInfo<'/users/new', '/users/new', Record<never, never>, Record<never, never>>,
    '/users/new/[...path]': RouteRecordInfo<'/users/new/[...path]', '/users/new/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/users/new/confirm': RouteRecordInfo<'/users/new/confirm', '/users/new/confirm', Record<never, never>, Record<never, never>>,
    '/users/new/input': RouteRecordInfo<'/users/new/input', '/users/new/input', Record<never, never>, Record<never, never>>,
  }
}
